[package]
name = "tomorrow-core"
version = "0.2.0"
authors = ["Valentin Fries <contact@fries.io>", "Vincent Milano <vincent_mot@hotmail.fr>"]

[dependencies]
error-chain = "0.11.0"
serde_json = "1.0.4"
hyper = "0.10.11"